version: "3.8"

services:
  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - zep_zep-network
    env_file:
      - ./.env
    volumes:
      - .:/app/

  smtp-service:
    image: axllent/mailpit
    restart: unless-stopped
    container_name: smtp
    networks:
      - zep_zep-network
    ports:
      - "8025:8025"
      - "1025:1025"

networks:
  zep_zep-network:
    external: true

volumes:
  bytebricks_mysql_data:
    external: true
