"""updated document name columns to be case sensitive

Revision ID: 04f0595d18bc
Revises: f057c0f4978a
Create Date: 2024-04-16 04:05:50.445090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f0595d18bc'
down_revision: Union[str, None] = 'f057c0f4978a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_documents', 'document_name',
                    existing_type=sa.String(length=255),
                    type_=sa.String(length=255, collation='utf8_bin'),
                    existing_nullable=False)
    op.alter_column('knowledgebase_documents', 'document_name',
                existing_type=sa.String(length=255),
                type_=sa.String(length=255, collation='utf8_bin'),
                existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_documents', 'document_name',
                    existing_type=sa.String(length=255),
                    type_=sa.String(length=255, collation='utf8_general_ci'),
                    existing_nullable=False)
    op.alter_column('knowledgebase_documents', 'document_name',
                existing_type=sa.String(length=255),
                type_=sa.String(length=255, collation='utf8_general_ci'),
                existing_nullable=False)
    # ### end Alembic commands ###
