"""Add composite index to kb and user docs table

Revision ID: 0695e9a6498f
Revises: aafd8b91eaf4
Create Date: 2024-04-28 03:14:44.705622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0695e9a6498f'
down_revision: Union[str, None] = 'aafd8b91eaf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_document_name', 'knowledgebase_documents', ['document_name'], unique=False)
    op.create_index('idx_user_id_document_name', 'user_documents', ['user_id', 'document_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id_document_name', table_name='user_documents')
    op.drop_index('idx_document_name', table_name='knowledgebase_documents')
    # ### end Alembic commands ###
