"""stripe data added

Revision ID: 072f27b5090d
Revises: c852eda0920a
Create Date: 2024-05-16 02:25:56.886438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '072f27b5090d'
down_revision: Union[str, None] = 'c852eda0920a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('paid', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('plan', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('stripeId', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('trial_expiry', mysql.DATETIME(fsp=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_expiry')
    op.drop_column('users', 'stripeId')
    op.drop_column('users', 'plan')
    op.drop_column('users', 'paid')
    # ### end Alembic commands ###
