"""revised_table

Revision ID: 387fda3268be
Revises: aef165b6d6df
Create Date: 2024-05-14 18:28:30.161521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '387fda3268be'
down_revision: Union[str, None] = 'aef165b6d6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial_expiry', mysql.DATETIME(fsp=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_expiry')
    # ### end Alembic commands ###
