"""streaming-table

Revision ID: 740f512a3779
Revises: 30f828d6a386
Create Date: 2024-04-17 14:49:42.363914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740f512a3779'
down_revision: Union[str, None] = '30f828d6a386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_config', sa.Column('llm_streaming', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_config', 'llm_streaming')
    # ### end Alembic commands ###
