"""revised_table

Revision ID: 894e020a1e6d
Revises: 607ce6d68dd1
Create Date: 2024-04-08 21:31:36.560043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894e020a1e6d'
down_revision: Union[str, None] = '607ce6d68dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'paid')
    # ### end Alembic commands ###
