"""added streaming param in admin config

Revision ID: aafd8b91eaf4
Revises: 04f0595d18bc
Create Date: 2024-04-19 04:15:33.569365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aafd8b91eaf4'
down_revision: Union[str, None] = '04f0595d18bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_config', sa.Column('llm_streaming', sa.Boolean(), nullable=False))
    op.alter_column('knowledgebase_documents', 'document_name',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=255),
               type_=sa.String(length=250, collation='utf8_bin'),
               nullable=True)
    op.alter_column('user_documents', 'document_name',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=255),
               type_=sa.String(length=250, collation='utf8_bin'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_documents', 'document_name',
               existing_type=sa.String(length=250, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=255),
               nullable=False)
    op.alter_column('knowledgebase_documents', 'document_name',
               existing_type=sa.String(length=250, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=255),
               nullable=False)
    op.drop_column('admin_config', 'llm_streaming')
    # ### end Alembic commands ###
