"""revised_table

Revision ID: aef165b6d6df
Revises: 0df4d2615f59
Create Date: 2024-05-13 15:58:23.041868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aef165b6d6df'
down_revision: Union[str, None] = '0df4d2615f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'plan',
               existing_type=mysql.ENUM('free', 'one_month', 'three_month', 'six_month'),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'plan',
               existing_type=sa.String(length=200),
               type_=mysql.ENUM('free', 'one_month', 'three_month', 'six_month'),
               existing_nullable=True)
    # ### end Alembic commands ###
