"""update composite index to kb and user docs table

Revision ID: c852eda0920a
Revises: 0695e9a6498f
Create Date: 2024-04-28 03:21:32.888322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c852eda0920a'
down_revision: Union[str, None] = '0695e9a6498f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_id_document_name_status', 'user_documents', ['user_id', 'document_name', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id_document_name_status', table_name='user_documents')
    # ### end Alembic commands ###
