"""updated file entry structure

Revision ID: f057c0f4978a
Revises: 607ce6d68dd1
Create Date: 2024-04-08 06:57:17.576618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f057c0f4978a'
down_revision: Union[str, None] = '607ce6d68dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledgebase_documents', sa.Column('status', sa.String(length=100), nullable=True))
    op.add_column('knowledgebase_documents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('knowledgebase_documents', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_knowledgebase_documents_status'), 'knowledgebase_documents', ['status'], unique=False)
    op.drop_column('knowledgebase_documents', 'uploaded_at')
    op.add_column('user_documents', sa.Column('status', sa.String(length=100), nullable=True))
    op.add_column('user_documents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user_documents', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_user_documents_status'), 'user_documents', ['status'], unique=False)
    op.drop_column('user_documents', 'uploaded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_documents', sa.Column('uploaded_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_index(op.f('ix_user_documents_status'), table_name='user_documents')
    op.drop_column('user_documents', 'created_at')
    op.drop_column('user_documents', 'updated_at')
    op.drop_column('user_documents', 'status')
    op.add_column('knowledgebase_documents', sa.Column('uploaded_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_index(op.f('ix_knowledgebase_documents_status'), table_name='knowledgebase_documents')
    op.drop_column('knowledgebase_documents', 'created_at')
    op.drop_column('knowledgebase_documents', 'updated_at')
    op.drop_column('knowledgebase_documents', 'status')
    # ### end Alembic commands ###
