name: Azure Container Apps Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile.cloud
          containerAppName: caira-v2-prod-backend
          acrName: unwildered
          imageToBuild: unwildered.azurecr.io/caira-v2-prod-backend:latest-${{ github.sha }}
          resourceGroup: CairaProduction
